create table if not exists products (
  id text primary key,
  category text not null check (category in ('Shoes', 'Sneakers', 'Slippers')),
  name text not null,
  tag text not null,
  price integer not null check (price >= 0),
  image_url text not null,
  description text not null,
  popularity integer not null default 0 check (popularity >= 0),
  status text not null default 'Active' check (status in ('Active', 'Draft', 'Archived')),
  created_at text not null,
  updated_at text not null
);

create table if not exists product_images (
  product_id text not null references products(id) on delete cascade,
  image_url text not null,
  position integer not null default 0 check (position >= 0),
  primary key (product_id, position)
);

create table if not exists product_sizes (
  product_id text not null references products(id) on delete cascade,
  size integer not null check (size > 0),
  stock integer not null default 0 check (stock >= 0),
  primary key (product_id, size)
);

create table if not exists customers (
  id text primary key,
  name text not null,
  email text not null unique,
  phone text,
  address text not null,
  city text not null,
  country text not null,
  created_at text not null,
  updated_at text not null
);

create table if not exists orders (
  id text primary key,
  customer_id text not null references customers(id),
  status text not null default 'Processing' check (status in ('Processing', 'Shipped', 'Delivered', 'Cancelled')),
  payment_status text not null default 'Pending' check (payment_status in ('Pending', 'Paid', 'Failed', 'Refunded')),
  payment_reference text unique,
  subtotal integer not null check (subtotal >= 0),
  shipping integer not null check (shipping >= 0),
  total integer not null check (total >= 0),
  delivery_email text not null,
  delivery_name text not null,
  delivery_address text not null,
  delivery_city text not null,
  delivery_country text not null,
  delivery_phone text,
  recipient_name text,
  recipient_phone text,
  recipient_address text,
  recipient_city text,
  recipient_country text,
  placed_at text not null,
  paid_at text,
  estimated_delivery text not null
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  product_id text not null references products(id),
  product_name text not null,
  size integer not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0)
);

create table if not exists returns (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id),
  reason text not null,
  status text not null default 'Requested' check (status in ('Requested', 'Approved', 'Rejected')),
  created_at text not null
);

create table if not exists admin_users (
  id text primary key,
  email text not null unique,
  password_hash text not null,
  created_at text not null
);

create table if not exists admin_sessions (
  token_hash text primary key,
  admin_id text not null references admin_users(id) on delete cascade,
  expires_at text not null,
  created_at text not null
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  title text not null,
  message text not null,
  order_id text,
  read_at text,
  created_at text not null
);

create table if not exists store_settings (
  key text primary key,
  value text not null,
  updated_at text not null
);

create table if not exists buyer_accounts (
  id text primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at text not null
);

create table if not exists buyer_sessions (
  token_hash text primary key,
  buyer_id text not null references buyer_accounts(id) on delete cascade,
  expires_at text not null,
  created_at text not null
);

create table if not exists carts (
  id text primary key,
  created_at text not null,
  updated_at text not null
);

create table if not exists cart_items (
  cart_id text not null references carts(id) on delete cascade,
  product_id text not null references products(id) on delete cascade,
  size integer not null,
  quantity integer not null check (quantity > 0),
  primary key (cart_id, product_id, size)
);

create table if not exists shipping_rates (
  location text primary key,
  standard integer not null check (standard >= 0),
  express integer not null check (express >= 0),
  updated_at text not null
);

create index if not exists products_status_created_at_idx on products(status, created_at desc);
create index if not exists orders_payment_status_idx on orders(payment_status);
create index if not exists admin_sessions_expiry_idx on admin_sessions(expires_at);
create index if not exists buyer_sessions_expiry_idx on buyer_sessions(expires_at);
create index if not exists notifications_unread_idx on notifications(read_at, created_at desc);
create unique index if not exists customers_email_lower_idx on customers(lower(email));
create unique index if not exists admin_users_email_lower_idx on admin_users(lower(email));
create unique index if not exists buyer_accounts_email_lower_idx on buyer_accounts(lower(email));

create or replace function execute_app_sql(query_text text, query_params jsonb default '[]'::jsonb, return_rows boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  rendered_query text := query_text;
  result jsonb := '[]'::jsonb;
  parameter_index integer;
  parameter_value jsonb;
  parameter_literal text;
begin
  query_params := case when jsonb_typeof(query_params) = 'array' then query_params else '[]'::jsonb end;
  parameter_index := jsonb_array_length(query_params);
  while parameter_index > 0 loop
    parameter_value := query_params -> (parameter_index - 1);
    parameter_literal := case jsonb_typeof(parameter_value)
      when 'null' then 'NULL'
      when 'string' then quote_nullable(parameter_value #>> '{}')
      else parameter_value::text
    end;
    rendered_query := regexp_replace(rendered_query, '\$' || parameter_index::text || '\M', parameter_literal, 'g');
    parameter_index := parameter_index - 1;
  end loop;

  if return_rows then
    execute format('select coalesce(jsonb_agg(row_to_json(result)), ''[]''::jsonb) from (%s) result', rendered_query) into result;
  else
    execute rendered_query;
  end if;
  return result;
end;
$$;

revoke all on function execute_app_sql(text, jsonb, boolean) from public, anon, authenticated;
grant execute on function execute_app_sql(text, jsonb, boolean) to service_role;

insert into shipping_rates (location, standard, express, updated_at) values
  ('Accra', 12, 28, now()::text),
  ('Kumasi', 18, 35, now()::text),
  ('Other', 25, 45, now()::text)
on conflict (location) do nothing;

insert into store_settings (key, value, updated_at) values
  ('storeName', 'Big Pee Kicks', now()::text),
  ('email', 'hello@bigpeekicks.com', now()::text),
  ('standardShipping', '12', now()::text),
  ('expressShipping', '28', now()::text),
  ('freeDeliveryThreshold', '200', now()::text),
  ('promoCode', 'BIGPEE10', now()::text),
  ('promoDiscount', '10', now()::text)
on conflict (key) do nothing;
